- name: Create a Repository and download the files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo 

- name: Install mongo 
  yum:
    name: mongodb-org
    state: present

- name: Chnage the IP address in mongod.conf file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'  

- name: Start MongoDB Service
  systemd:
    name: mongod
    state: started
    enabled: yes


- name: Download the schema of mongodb
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Run a catalogue file containing MongoDB 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: Run a user file containing MongoDB 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes


