- name: Create a mysql repository
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove the mariadb lib
  yum:
    name: mariadb-libs
    state: absent


- name: Install MySQL Serverr
  yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: present


- name: Start mysql 
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

